version: "2"

services: 
  elkweb: 
    container_name: elkweb
    image: webapp.rtsys:5000/elk/elklive:latest
    ports: 
      - 10.6.0.61:8082:8080
    restart: "no"
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      start_period: 2m
